services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: orders_management_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-management-api:
    build:
      context: ..
      dockerfile: OrderManagementAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=orders_management_api;Username=postgres;Password=qwerty"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
